openapi: 3.0.0
info:
  title: API de Avales
  version: 0.1.0
  description: API para manejar documentos de avales.
servers:
  - url: https://avales-web.vercel.app/ # Cambia esto por la URL base de tu API
    description: Servidor local
tags:
  - name: Usuarios
    description: Operaciones relacionadas con los usuarios
  - name: Roles
    description: Operaciones relacionadas con los roles
  - name: Disciplinas
    description: Operaciones relacionadas con las disciplinas
paths:
  /api/usuarios:
    get:
      summary: Obtener usuarios
      tags:
        - Usuarios
      description: Obtiene una lista paginada de usuarios o un usuario específico por ID.
      parameters:
        - name: id
          in: query
          description: ID del usuario a buscar
          schema:
            type: integer
        - name: page
          in: query
          description: Número de página para la paginación
          schema:
            type: integer
      responses:
        "200":
          description: Lista de usuarios obtenida correctamente
        "400":
          description: Error en los parámetros de entrada
        "404":
          description: Usuario no encontrado
    post:
      summary: Crear un nuevo usuario
      tags:
        - Usuarios
      description: Crea un nuevo usuario con los datos proporcionados.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                nombre:
                  type: string
                apellido:
                  type: string
                cedula:
                  type: string
                categoria_id:
                  type: integer
                disciplina_id:
                  type: integer
                roles:
                  type: array
                  items:
                    type: integer
      responses:
        "201":
          description: Usuario creado correctamente
        "400":
          description: Error en los datos enviados
  /api/usuarios/{id}:
    put:
      summary: Actualizar un usuario
      tags:
        - Usuarios
      description: Actualiza un usuario existente por su ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                nombre:
                  type: string
                apellido:
                  type: string
                cedula:
                  type: string
                categoria_id:
                  type: integer
                disciplina_id:
                  type: integer
                roles:
                  type: array
                  items:
                    type: integer
      responses:
        "200":
          description: Usuario actualizado correctamente
        "400":
          description: Error en los datos enviados
    delete:
      summary: Eliminar un usuario
      tags:
        - Usuarios
      description: Elimina un usuario por su ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Usuario eliminado correctamente
        "400":
          description: Error en la petición
  /api/roles:
    get:
      summary: Obtener roles
      tags:
        - Roles
      description: Obtiene una lista paginada de roles o un rol específico por ID.
      parameters:
        - name: id
          in: query
          description: ID del rol a buscar
          schema:
            type: integer
        - name: page
          in: query
          description: Número de página para la paginación
          schema:
            type: integer
      responses:
        "200":
          description: Lista de roles obtenida correctamente
        "400":
          description: Error en los parámetros de entrada
        "404":
          description: Rol no encontrado
    post:
      summary: Crear un nuevo rol
      tags:
        - Roles
      description: Crea un nuevo rol con los datos proporcionados.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                descripcion:
                  type: string
      responses:
        "201":
          description: Rol creado correctamente
        "400":
          description: Error en los datos enviados
  /api/roles/{id}:
    put:
      summary: Actualizar un rol
      tags:
        - Roles
      description: Actualiza un rol existente por su ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                descripcion:
                  type: string
      responses:
        "200":
          description: Rol actualizado correctamente
        "400":
          description: Error en los datos enviados
    delete:
      summary: Eliminar un rol
      tags:
        - Roles
      description: Elimina un rol por su ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Rol eliminado correctamente
        "400":
          description: Error en la petición
  /api/disciplinas:
    get:
      summary: Obtener disciplinas
      tags:
        - Disciplinas
      description: Obtiene una lista de disciplinas con paginación.
      parameters:
        - name: id
          in: query
          description: ID de la disciplina a obtener.
          required: false
          schema:
            type: integer
        - name: page
          in: query
          description: Número de página para la paginación.
          required: false
          schema:
            type: integer
            default: 1
      responses:
        "200":
          description: Lista de disciplinas obtenida correctamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  pagina:
                    type: integer
                  totalPaginas:
                    type: integer
                  totalDisciplinas:
                    type: integer
                  disciplinas:
                    type: array
                    items:
                      $ref: "#/components/schemas/Disciplina"
        "400":
          description: Parámetro inválido en la solicitud.
        "404":
          description: Disciplina no encontrada.
        "500":
          description: Error interno del servidor.
    post:
      summary: Crear una nueva disciplina
      tags:
        - Disciplinas
      description: Crea una nueva disciplina con el nombre proporcionado.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - nombre
              properties:
                nombre:
                  type: string
      responses:
        "201":
          description: Disciplina creada exitosamente.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Disciplina"
        "400":
          description: Datos inválidos en la solicitud.
        "500":
          description: Error al crear la disciplina.
  /api/disciplinas/{id}:
    put:
      summary: Actualizar una disciplina
      tags:
        - Disciplinas
      description: Actualiza el nombre de una disciplina existente.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - nombre
              properties:
                id:
                  type: integer
                nombre:
                  type: string
      responses:
        "200":
          description: Disciplina actualizada correctamente.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Disciplina"
        "400":
          description: Datos inválidos en la solicitud.
        "500":
          description: Error al actualizar la disciplina.
    delete:
      summary: Eliminar una disciplina
      tags:
        - Disciplinas
      description: Elimina una disciplina por su ID.
      parameters:
        - name: id
          in: query
          description: ID de la disciplina a eliminar.
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Disciplina eliminada correctamente.
        "400":
          description: ID de disciplina no válido.
        "500":
          description: Error al eliminar la disciplina.
